import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName : "Control de Stock",
  appleWebApp : {
    capable : true,
    title : "Control de Stock",
    statusBarStyle : "black-translucent"
  },
  formatDetection : {
    telephone : false
  },
  themeColor : "#000000",
  icons : {
    icon : "/icons/icon-512x512.png",
    apple : "/icons/icon-512x512.png"
  },
  manifest : "/manifest.json",
  twitter : {
    card : "summary_large_image",
    site : "@site",
    creator : "@creator",
    "images" : "https://example.com/og.png"
  },
  openGraph : {
    type : "website",
    url : "https://example.com",
    title : "My Website",
    description : "My Website Description",
    siteName : "My Website",
    images : [
      {
        url : "https://example.com/og.png",
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={cn(inter.className, "min-h-dvh flex flex-col bg-gradient-to-br dark:from-background dark:to-secondary from-primary-foreground")}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Header /> */}
            {children}
            <Toaster />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
